site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      toc_depth: 6
      permalink: "#"
      baselevel: 1
      separator: "_"
plugins:
  - search
  - autolinks
  - table-reader
  - pdf-export
  - awesome-nav
  