site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
  features:
    - navigation.top
markdown_extensions:
  - toc:
      toc_depth: 5
      permalink: true
      baselevel: 2
      separator: "_"
plugins:
  - search
  - autolinks
  - table-reader
  - pdf-export
  - awesome-nav
