site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      toc_depth: 5
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - search
  - autolinks
  - table-reader
  - pdf-export
  - awesome-nav