site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
  features:
    - navigation.top
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
  - autolinks
  - table-reader
  - pdf-export
  - awesome-nav
