site_name: Cardiac Gene2Phenotype Gene Panel
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      toc_depth: 5
      permalink: "#"
      baselevel: 1
      separator: "_"
plugins:
  - search
  - autolinks
  