site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
  include_sidebar: true
  features:
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
plugins:
  - search
  - awesome-nav
nav:
  - Cardiac Gene2Phenotype: 
    - index.md
