site_name: Cardiac Gene2Phenotype
theme:
  name: readthedocs
  features:
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
plugins:
  - search
  - table-reader
  - pdf-export
  - awesome-nav
nav:
  - Cardiac Gene2Phenotype: index.md
